devices:
  - name: R1 GDL
    ip: "1.1.1.1"
    snmp_config: cisco
  - name: R2 Monterrey
    ip: "2.2.2.2"
    snmp_config: cisco
  - name: R3 CDMX
    ip: "3.3.3.3"
    snmp_config: cisco

snmp_configs:
  cisco:
    snmp:
      community: "equipo3"
    oids:
      - name: "hostname"
        oid: "1.3.6.1.2.1.1.5.0"
        type: "string"
      - name: "system_description"
        oid: "1.3.6.1.2.1.1.1.0"
        type: "string"
      - name: "uptime"
        oid: "1.3.6.1.2.1.1.3.0"
        type: "seconds"
      # - name: "memory"
      #   oid: "1.3.6.1.4.1.9.9.48.1.1.1.5.1"
      - name: "interfaces_number"
        oid: "1.3.6.1.2.1.2.1.0"
        type: "integer"
        sub_oids:
          - name: "interface_description"
            oid: "1.3.6.1.2.1.2.2.1.2"
            type: "string"
          - name: "interface_mac"
            oid: "1.3.6.1.2.1.2.2.1.6"
            type: "string"
          - name: "interface_last_change"
            oid: "1.3.6.1.2.1.2.2.1.9"
            type: "seconds"
          - name: "interface_status"
            oid: "1.3.6.1.2.1.2.2.1.8"
            type: "integer"